# config.toml

# Sample of parameters in the program
[parameters]
no_certs = true
port = 8071
www_dir = "www"
firmware_dir = "firmware"
url_firmware = "firmware"

[metadata]
#version = true

[logging]
verbose = true
