# database_interface.py

from typing import Protocol

from ota_http_server.core.data_models import User, Project, Device

class DatabaseInterface(Protocol):

    def init_db(self) -> None:
        ...

    def migrate(self) -> None:
        ...

    def rollback(self) -> None:
        ...

    def add_user(self, user: User) -> User:
        ...

    def enable_user_by_id(self, user_id: int) -> None:
        ...

    def enable_user_by_username(self, username: str) -> None:
        ...

    def disable_user_by_id(self, user_id: int) -> None:
        ...

    def disable_user_by_username(self, username: str) -> None:
        ...

    def user_get_by_id(self, user_id: int) -> User | None:
        ...

    def user_get_by_username(self, username: str) -> User | None:
        ...

    def user_get_list(self) -> list[User]:
        ...

    def add_project(self, project: Project) -> Project:
        ...

    def enable_project_by_id(self, id: int) -> None:
        ...

    def enable_project_by_name(self, name: str) -> None:
        ...

    def disable_project_by_id(self, id: int) -> None:
        ...

    def disable_project_by_name(self, name: str) -> None:
        ...

    def get_project_by_id(self, id: int) -> Project | None:
        ...

    def get_project_by_name(self, name: str) -> Project | None:
        ...

    def project_get_list(self) -> list[Project]:
        ...

    def add_device(self, device: Device) -> Device:
        ...

    def enable_device_by_id(self, id: int) -> None:
        ...

    def enable_device_by_name(self, name: str) -> None:
        ...

    def disable_device_by_id(self, id: int) -> None:
        ...

    def disable_device_by_name(self, name: str) -> None:
        ...

    def get_device_by_id(self, id: int) -> Device | None:
        ...

    def get_device_by_name(self, name: str) -> Device | None:
        ...

    def device_get_list(self) -> list[Device]:
        ...
